require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.6
  DisplayCopNames: true
  Exclude:
    - Rakefile
    - cache/**/*
    - bin/**/*
    - spec/dummy/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

  # Enforces empty line after multiline condition.
Layout/EmptyLineAfterMultilineCondition:
  Enabled: true

# Checks for a line break before the first element in a multi-line array.
Layout/FirstArrayElementLineBreak:
  Enabled: true

# Checks for a line break before the first element in a multi-line hash.
Layout/FirstHashElementLineBreak:
  Enabled: true

# Checks that each item in a multi-line array literal starts on a separate line.
Layout/MultilineArrayLineBreaks:
  Enabled: true

# Check for a newline after the assignment operator in multi-line assignments.
Layout/MultilineAssignmentLayout:
  Enabled: true

# Checks that each item in a multi-line hash literal starts on a separate line.
Layout/MultilineHashKeyLineBreaks:
  Enabled: true

# Checks that each argument in a multi-line method call starts on a separate line.
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

# Checks unsafe usage of number conversion methods.
Lint/NumberConversion:
  Enabled: true

# Enforces using `def self.method_name` or `class << self` to define class methods.
Style/ClassMethodsDefinitions:
  Enabled: true
  EnforcedStyle: self_class

# Check that class- and module constants have visibility declarations.
Style/ConstantVisibility:
  Enabled: true

# Document classes and non-namespace modules.
Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/dirty_seed/engine.rb'
    - 'lib/dirty_seed.rb'

# Checks for missing documentation comment for public methods.
Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true

# Avoid trailing inline comments.
Style/InlineComment:
  Enabled: true

# Avoid chaining a method call on a do...end block.
Style/MethodCalledOnDoEndBlock:
  Enabled: true

# Avoid multi-line method signatures.
Style/MultilineMethodSignature:
  Enabled: true

# Don't use option hashes when you can use keyword arguments.
Style/OptionHash:
  Enabled: true

# Use return instead of return nil.
Style/ReturnNil:
  Enabled: true

# Prefer `Object#__send__` or `Object#public_send` to `send`, as `send` may overlap with existing methods.
Style/Send:
  Enabled: true

# Prefer symbols instead of strings as hash keys.
Style/StringHashKeys:
  Enabled: true

# Checks for useless trailing commas in block arguments.
Style/TrailingCommaInBlockArgs:
  Enabled: true

# Allow more lines in specs
RSpec/ExampleLength:
  Max: 8

# Allow more nesting for detailed specs
RSpec/NestedGroups:
  Max: 5

# Allow more expectations in one spec
RSpec/MultipleExpectations:
  Max: 3